/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto1.gui;

/**
 *
 * @author andresbucarello
 */
public class AgregarRuta extends javax.swing.JPanel {

    /**
     * Creates new form AgregarRuta
     */
    public AgregarRuta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRetroceder = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rutasDisponibles = new javax.swing.JList<>();
        botonAgregarRuta = new javax.swing.JButton();
        titulo4 = new javax.swing.JLabel();
        botonAgregarAlmacen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rutasAgregadas = new javax.swing.JList<>();
        botonGuardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        comentario1 = new javax.swing.JTextArea();
        comentario2 = new javax.swing.JLabel();
        comentario3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRetroceder.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceder.png"))); // NOI18N
        botonRetroceder.setBorder(null);
        botonRetroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetrocederActionPerformed(evt);
            }
        });
        add(botonRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        titulo1.setFont(new java.awt.Font("Silom", 0, 48)); // NOI18N
        titulo1.setText("AGREGAR RUTA");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        titulo2.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo2.setText("SELECCIONE EL ALMACEN :");
        add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 580, 10));

        titulo3.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo3.setText("RUTAS DISPONIBLES");
        add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 30));

        rutasDisponibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(rutasDisponibles);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 220));

        botonAgregarRuta.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonAgregarRuta.setText(">>");
        botonAgregarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarRutaActionPerformed(evt);
            }
        });
        add(botonAgregarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 60, 40));

        titulo4.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo4.setText("RUTAS AGREGADAS");
        add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 220, 30));

        botonAgregarAlmacen.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonAgregarAlmacen.setText("Agregar Rutas");
        botonAgregarAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAlmacenActionPerformed(evt);
            }
        });
        add(botonAgregarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 440, -1));

        rutasAgregadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(rutasAgregadas);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 220, 220));

        botonGuardar.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 120, -1));

        comentario1.setColumns(20);
        comentario1.setFont(new java.awt.Font("Helvetica Neue", 0, 6)); // NOI18N
        comentario1.setRows(5);
        comentario1.setTabSize(5);
        comentario1.setText("// Se activa solo\ncuando se haya\nseleeccionado un\nalmacen para ruta");
        jScrollPane3.setViewportView(comentario1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 70, -1));

        comentario2.setFont(new java.awt.Font("Helvetica Neue", 0, 6)); // NOI18N
        comentario2.setText("// Se activa cuando se hayan agregado al menos dos rutas");
        add(comentario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 160, 10));

        comentario3.setText("// JOP para pedir la distancia");
        add(comentario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetrocederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRetrocederActionPerformed

    private void botonAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarRutaActionPerformed

    private void botonAgregarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarAlmacenActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarAlmacen;
    private javax.swing.JButton botonAgregarRuta;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRetroceder;
    private javax.swing.JTextArea comentario1;
    private javax.swing.JLabel comentario2;
    private javax.swing.JLabel comentario3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> rutasAgregadas;
    private javax.swing.JList<String> rutasDisponibles;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
