/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto1.gui;

/**
 *
 * @author andresbucarello
 */
public class ModificarStock extends javax.swing.JPanel {

    /**
     * Creates new form ModificarStockk
     */
    public ModificarStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRetroceder = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        listaAlmacenes = new javax.swing.JComboBox<>();
        titulo3 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        fieldPrecio = new javax.swing.JTextField();
        botonComprobar1 = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        listaAlmacenes1 = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(630, 450));
        setMinimumSize(new java.awt.Dimension(630, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRetroceder.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceder.png"))); // NOI18N
        botonRetroceder.setBorder(null);
        botonRetroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetrocederActionPerformed(evt);
            }
        });
        add(botonRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        titulo1.setFont(new java.awt.Font("Silom", 0, 48)); // NOI18N
        titulo1.setText("MODIFICAR STOCK");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        titulo2.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo2.setText("SELECCIONE EL ALMACEN :");
        add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        listaAlmacenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(listaAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 290, -1));

        titulo3.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo3.setText("SELECCIONE EL NOMBRE DEL PRODUCTO :");
        add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 290, 20));

        titulo4.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        titulo4.setText("INGRESE LA CANTIDAD A AUMENTAR  DEL PRODUCTO :");
        add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 370, 20));

        fieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPrecioActionPerformed(evt);
            }
        });
        add(fieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 80, 20));

        botonComprobar1.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonComprobar1.setText("COMPROBAR");
        botonComprobar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobar1ActionPerformed(evt);
            }
        });
        add(botonComprobar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, 20));

        botonGuardar.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 120, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 580, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 580, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 580, 20));

        listaAlmacenes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(listaAlmacenes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetrocederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRetrocederActionPerformed

    private void fieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPrecioActionPerformed

    private void botonComprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComprobar1ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprobar1;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRetroceder;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> listaAlmacenes;
    private javax.swing.JComboBox<String> listaAlmacenes1;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
